version: "3.8"

services:
  ollama:
    build:
      context: ./movie-web-app-backend
      dockerfile: Ollama.Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./movie-web-app-backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./movie-web-app-backend:/app
    working_dir: /app
