version: "3.8"

services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ollama-models:/root/.ollama

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    restart: always

volumes:
  ollama-models:
